// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5L7frB0tfXMedsC1FUz_JXdHSxstZEHk',
    appId: '1:480666241444:web:8db2b09872823147029931',
    messagingSenderId: '480666241444',
    projectId: 'bd-immam',
    authDomain: 'bd-immam.firebaseapp.com',
    storageBucket: 'bd-immam.firebasestorage.app',
    measurementId: 'G-5WLBLQBD5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrD36qPIBvSOGJjplFs3nxrZgoI3ihQ28',
    appId: '1:480666241444:android:931249bb901b92b7029931',
    messagingSenderId: '480666241444',
    projectId: 'bd-immam',
    storageBucket: 'bd-immam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSAtH3szEuSz8NyLKV0vo3srdB8OJZSls',
    appId: '1:480666241444:ios:0634b95809ca6541029931',
    messagingSenderId: '480666241444',
    projectId: 'bd-immam',
    storageBucket: 'bd-immam.firebasestorage.app',
    iosBundleId: 'com.example.immam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSAtH3szEuSz8NyLKV0vo3srdB8OJZSls',
    appId: '1:480666241444:ios:0634b95809ca6541029931',
    messagingSenderId: '480666241444',
    projectId: 'bd-immam',
    storageBucket: 'bd-immam.firebasestorage.app',
    iosBundleId: 'com.example.immam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5L7frB0tfXMedsC1FUz_JXdHSxstZEHk',
    appId: '1:480666241444:web:d951b4b5320c6a21029931',
    messagingSenderId: '480666241444',
    projectId: 'bd-immam',
    authDomain: 'bd-immam.firebaseapp.com',
    storageBucket: 'bd-immam.firebasestorage.app',
    measurementId: 'G-K1KTX1ES5F',
  );
}
